/*SQL Coding for training with ORACAL "https://livesql.oracle.com/apex/f?p=590:1:11257469250555::NO:::"
I use Oracal for training with SQL Code.
*/


--1 AND, IN, NOT EXISTS und OR Operator in the WHERE Clause
SELECT *
FROM HR.EMPLOYEES
WHERE SALARY > 10000 and Manager_ID = 100 and DEPARTMENT_ID = 90
ORDER BY SALARY DESC

SELECT *
FROM HR.EMPLOYEES
WHERE SALARY > 10000 or Manager_ID = 100 or not DEPARTMENT_ID = 90
ORDER BY SALARY DESC

SELECT *
FROM HR.DEPARTMENTS  --HR.EMPLOYEES
WHERE EXISTS (SELECT MANAGER_ID FROM HR.EMPLOYEES WHERE HR.EMPLOYEES.MANAGER_ID = HR.DEPARTMENTS.MANAGER_ID and SALARY < 17000);


